name: build
on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: "https://npm.pkg.github.com"
      - name: set token
        if: contains(github.ref, 'master')
        run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > ${HOME}/.npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: yarn install
        run: yarn install
      - name: login
        run: npm login --registry=https://npm.pkg.github.com/
      - name: publish
        if: contains(github.ref, 'master')
        run: npm run publish:ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}