name: Publish
on:
  push:
    branches:
      - master
jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup git user
          command: |
            git config --global user.email "r.sqrrnbn9909@gmail.com"
            git config --global user.name "khrtz"
      - name: npm-publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: publish:ci
